# .readthedocs.yaml

version: 2

build:
  os: "ubuntu-22.04"  # Set the OS to a supported Ubuntu version
  image: latest  # Use the latest build image provided by RTD

sphinx:
  configuration: source/conf.py  # Path to your Sphinx config file

python:
  version: 3.9  # Python version
  install:
    - requirements: source/requirements.txt  # Path to your requirements file
